
[MeasureSmoothed0]
Group=AL
Measure=Calc
Formula=(Measure1+Measure1+Measure2)/12
AverageSize=#AvgSoundLevel#

[MeasureSmoothed1]
Group=AL
Measure=Calc
Formula=(Measure1+Measure1+Measure2)/10
AverageSize=#AvgSoundLevel#

[MeasureSmoothed2]
Group=AL
Measure=Calc
Formula=(Measure1+Measure2+Measure3)/8
AverageSize=#AvgSoundLevel#

[MeasureSmoothed3]
Group=AL
Measure=Calc
Formula=(Measure2+Measure3+Measure4)/7
AverageSize=#AvgSoundLevel#

[MeasureSmoothed4]
Group=AL
Measure=Calc
Formula=(Measure3+Measure4+Measure5)/6
AverageSize=#AvgSoundLevel#

[MeasureSmoothed5]
Group=AL
Measure=Calc
Formula=(Measure4+Measure5+Measure6)/5
AverageSize=#AvgSoundLevel#

[MeasureSmoothed6]
Group=AL
Measure=Calc
Formula=(Measure5+Measure6+Measure7)/4
AverageSize=#AvgSoundLevel#

[MeasureSmoothed7]
Group=AL
Measure=Calc
Formula=(Measure6+Measure7+Measure8)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed8]
Group=AL
Measure=Calc
Formula=(Measure7+Measure8+Measure9)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed9]
Group=AL
Measure=Calc
Formula=(Measure8+Measure9+Measure10)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed10]
Group=AL
Measure=Calc
Formula=(Measure9+Measure10+Measure11)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed11]
Group=AL
Measure=Calc
Formula=(Measure10+Measure11+Measure12)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed12]
Group=AL
Measure=Calc
Formula=(Measure11+Measure12+Measure13)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed13]
Group=AL
Measure=Calc
Formula=(Measure12+Measure13+Measure14)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed14]
Group=AL
Measure=Calc
Formula=(Measure13+Measure14+Measure15)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed15]
Group=AL
Measure=Calc
Formula=(Measure14+Measure15+Measure16)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed16]
Group=AL
Measure=Calc
Formula=(Measure15+Measure16+Measure17)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed17]
Group=AL
Measure=Calc
Formula=(Measure16+Measure17+Measure18)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed18]
Group=AL
Measure=Calc
Formula=(Measure17+Measure18+Measure19)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed19]
Group=AL
Measure=Calc
Formula=(Measure18+Measure19+Measure20)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed20]
Group=AL
Measure=Calc
Formula=(Measure19+Measure20+Measure21)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed21]
Group=AL
Measure=Calc
Formula=(Measure20+Measure21+Measure22)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed22]
Group=AL
Measure=Calc
Formula=(Measure21+Measure22+Measure23)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed23]
Group=AL
Measure=Calc
Formula=(Measure22+Measure23+Measure24)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed24]
Group=AL
Measure=Calc
Formula=(Measure23+Measure24+Measure25)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed25]
Group=AL
Measure=Calc
Formula=(Measure24+Measure25+Measure26)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed26]
Group=AL
Measure=Calc
Formula=(Measure25+Measure26+Measure27)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed27]
Group=AL
Measure=Calc
Formula=(Measure26+Measure27+Measure28)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed28]
Group=AL
Measure=Calc
Formula=(Measure27+Measure28+Measure29)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed29]
Group=AL
Measure=Calc
Formula=(Measure28+Measure29+Measure30)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed30]
Group=AL
Measure=Calc
Formula=(Measure29+Measure30+Measure31)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed31]
Group=AL
Measure=Calc
Formula=(Measure30+Measure31+Measure32)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed32]
Group=AL
Measure=Calc
Formula=(Measure31+Measure32+Measure33)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed33]
Group=AL
Measure=Calc
Formula=(Measure32+Measure33+Measure34)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed34]
Group=AL
Measure=Calc
Formula=(Measure33+Measure34+Measure35)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed35]
Group=AL
Measure=Calc
Formula=(Measure34+Measure35+Measure36)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed36]
Group=AL
Measure=Calc
Formula=(Measure35+Measure36+Measure37)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed37]
Group=AL
Measure=Calc
Formula=(Measure36+Measure37+Measure38)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed38]
Group=AL
Measure=Calc
Formula=(Measure37+Measure38+Measure39)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed39]
Group=AL
Measure=Calc
Formula=(Measure38+Measure39+Measure40)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed40]
Group=AL
Measure=Calc
Formula=(Measure39+Measure40+Measure41)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed41]
Group=AL
Measure=Calc
Formula=(Measure40+Measure41+Measure42)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed42]
Group=AL
Measure=Calc
Formula=(Measure41+Measure42+Measure43)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed43]
Group=AL
Measure=Calc
Formula=(Measure42+Measure43+Measure44)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed44]
Group=AL
Measure=Calc
Formula=(Measure43+Measure44+Measure45)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed45]
Group=AL
Measure=Calc
Formula=(Measure44+Measure45+Measure46)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed46]
Group=AL
Measure=Calc
Formula=(Measure45+Measure46+Measure47)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed47]
Group=AL
Measure=Calc
Formula=(Measure46+Measure47+Measure48)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed48]
Group=AL
Measure=Calc
Formula=(Measure47+Measure48+Measure49)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed49]
Group=AL
Measure=Calc
Formula=(Measure48+Measure49+Measure50)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed50]
Group=AL
Measure=Calc
Formula=(Measure49+Measure50+Measure51)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed51]
Group=AL
Measure=Calc
Formula=(Measure50+Measure51+Measure52)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed52]
Group=AL
Measure=Calc
Formula=(Measure51+Measure52+Measure53)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed53]
Group=AL
Measure=Calc
Formula=(Measure52+Measure53+Measure54)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed54]
Group=AL
Measure=Calc
Formula=(Measure53+Measure54+Measure55)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed55]
Group=AL
Measure=Calc
Formula=(Measure54+Measure55+Measure56)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed56]
Group=AL
Measure=Calc
Formula=(Measure55+Measure56+Measure57)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed57]
Group=AL
Measure=Calc
Formula=(Measure56+Measure57+Measure58)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed58]
Group=AL
Measure=Calc
Formula=(Measure57+Measure58+Measure59)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed59]
Group=AL
Measure=Calc
Formula=(Measure58+Measure59+Measure60)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed60]
Group=AL
Measure=Calc
Formula=(Measure59+Measure60+Measure61)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed61]
Group=AL
Measure=Calc
Formula=(Measure60+Measure61+Measure62)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed62]
Group=AL
Measure=Calc
Formula=(Measure61+Measure62+Measure63)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed63]
Group=AL
Measure=Calc
Formula=(Measure62+Measure63+Measure64)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed64]
Group=AL
Measure=Calc
Formula=(Measure63+Measure64+Measure65)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed65]
Group=AL
Measure=Calc
Formula=(Measure64+Measure65+Measure66)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed66]
Group=AL
Measure=Calc
Formula=(Measure65+Measure66+Measure67)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed67]
Group=AL
Measure=Calc
Formula=(Measure66+Measure67+Measure68)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed68]
Group=AL
Measure=Calc
Formula=(Measure67+Measure68+Measure69)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed69]
Group=AL
Measure=Calc
Formula=(Measure68+Measure69+Measure70)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed70]
Group=AL
Measure=Calc
Formula=(Measure69+Measure70+Measure71)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed71]
Group=AL
Measure=Calc
Formula=(Measure70+Measure71+Measure72)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed72]
Group=AL
Measure=Calc
Formula=(Measure71+Measure72+Measure73)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed73]
Group=AL
Measure=Calc
Formula=(Measure72+Measure73+Measure74)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed74]
Group=AL
Measure=Calc
Formula=(Measure73+Measure74+Measure75)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed75]
Group=AL
Measure=Calc
Formula=(Measure74+Measure75+Measure76)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed76]
Group=AL
Measure=Calc
Formula=(Measure75+Measure76+Measure77)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed77]
Group=AL
Measure=Calc
Formula=(Measure76+Measure77+Measure78)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed78]
Group=AL
Measure=Calc
Formula=(Measure77+Measure78+Measure79)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed79]
Group=AL
Measure=Calc
Formula=(Measure78+Measure79+Measure80)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed80]
Group=AL
Measure=Calc
Formula=(Measure79+Measure80+Measure81)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed81]
Group=AL
Measure=Calc
Formula=(Measure80+Measure81+Measure82)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed82]
Group=AL
Measure=Calc
Formula=(Measure81+Measure82+Measure83)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed83]
Group=AL
Measure=Calc
Formula=(Measure82+Measure83+Measure84)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed84]
Group=AL
Measure=Calc
Formula=(Measure83+Measure84+Measure85)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed85]
Group=AL
Measure=Calc
Formula=(Measure84+Measure85+Measure86)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed86]
Group=AL
Measure=Calc
Formula=(Measure85+Measure86+Measure87)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed87]
Group=AL
Measure=Calc
Formula=(Measure86+Measure87+Measure88)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed88]
Group=AL
Measure=Calc
Formula=(Measure87+Measure88+Measure89)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed89]
Group=AL
Measure=Calc
Formula=(Measure88+Measure89+Measure90)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed90]
Group=AL
Measure=Calc
Formula=(Measure89+Measure90+Measure91)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed91]
Group=AL
Measure=Calc
Formula=(Measure90+Measure91+Measure92)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed92]
Group=AL
Measure=Calc
Formula=(Measure91+Measure92+Measure93)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed93]
Group=AL
Measure=Calc
Formula=(Measure92+Measure93+Measure94)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed94]
Group=AL
Measure=Calc
Formula=(Measure93+Measure94+Measure95)/3
AverageSize=#AvgSoundLevel#

[MeasureSmoothed95]
Group=AL
Measure=Calc
Formula=(Measure94+Measure95+Measure96)/4
AverageSize=#AvgSoundLevel#

[MeasureSmoothed96]
Group=AL
Measure=Calc
Formula=(Measure95+Measure96+Measure97)/5
AverageSize=#AvgSoundLevel#

[MeasureSmoothed97]
Group=AL
Measure=Calc
Formula=(Measure96+Measure97+Measure98)/6
AverageSize=#AvgSoundLevel#

[MeasureSmoothed98]
Group=AL
Measure=Calc
Formula=(Measure97+Measure98+Measure99)/7
AverageSize=#AvgSoundLevel#

[MeasureSmoothed99]
Group=AL
Measure=Calc
Formula=(Measure98+Measure99+Measure99)/8
AverageSize=#AvgSoundLevel#

