[MeterBar0]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth0]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar1]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth1]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar2]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth2]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar3]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth3]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar4]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth4]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar5]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth5]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar6]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth6]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar7]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth7]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar8]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth8]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar9]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth9]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar10]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth10]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar11]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth11]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar12]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth12]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar13]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth13]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar14]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth14]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar15]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth15]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar16]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth16]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar17]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth17]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar18]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth18]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar19]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth19]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar20]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth20]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar21]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth21]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar22]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth22]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar23]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth23]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar24]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth24]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar25]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth25]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar26]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth26]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar27]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth27]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar28]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth28]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar29]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth29]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar30]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth30]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar31]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth31]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar32]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth32]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar33]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth33]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar34]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth34]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar35]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth35]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar36]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth36]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar37]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth37]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar38]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth38]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar39]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth39]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar40]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth40]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar41]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth41]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar42]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth42]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar43]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth43]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar44]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth44]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar45]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth45]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar46]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth46]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar47]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth47]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar48]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth48]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar49]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth49]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar50]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth50]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar51]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth51]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar52]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth52]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar53]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth53]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar54]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth54]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar55]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth55]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar56]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth56]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar57]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth57]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar58]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth58]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar59]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth59]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar60]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth60]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar61]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth61]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar62]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth62]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar63]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth63]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar64]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth64]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar65]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth65]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar66]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth66]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar67]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth67]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar68]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth68]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar69]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth69]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar70]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth70]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar71]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth71]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar72]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth72]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar73]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth73]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar74]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth74]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar75]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth75]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar76]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth76]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar77]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth77]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar78]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth78]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar79]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth79]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar80]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth80]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar81]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth81]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar82]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth82]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar83]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth83]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar84]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth84]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar85]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth85]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar86]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth86]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1

[MeterBar87]
Meter=Shape
X=10R
Y=800
Shape=Rectangle 0,0,14,(-800*[MeasureBandSmooth87]),8 | Fill Color 250,191,255,173 | StrokeWidth 0
DynamicVariables=1
